### ISSUE TITLE
How to Download Input Datasets?

### ISSUE THREAD

**Issue by LQW-panpan** [hblasins/uwSim#1]

**Comment by hblasins** [comment]
The datasets are stored at Stanford Digital Repository at:
https://searchworks.stanford.edu/view/wp894vt1248

This is an open repository, anyone can access the data (you don't have to be affiliated with Stanford).

**Comment by LQW-panpan** [comment]
Thank you very much for your patience, we have successfully found the datasets.We are very interested in your work and thank you for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hblasins/uwSim"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 凌晨5:14
收件人:&nbsp;"hblasins/uwSim"<uwSim@noreply.github.com&gt;;
抄送:&nbsp;"淡抹の笑颜"<2412307254@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hblasins/uwSim] How to Download Input Datasets? (#1)





 
The datasets are stored at Stanford Digital Repository at:
 https://searchworks.stanford.edu/view/wp894vt1248
 
This is an open repository, anyone can access the data (you don't have to be affiliated with Stanford).
